name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    strategy:
      matrix:
        app: [ hello-rust ]
        rust-toolchain: [ stable, beta ]

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/${{ matrix.app }}

    steps:
    - uses: actions/checkout@v4
    - name: Rust version override
      run: rustup override set ${{ matrix.rust-toolchain }}
    - name: Rust version check
      run: rustup --version
    - name: Rust components
      run: rustup component add rustfmt
    - name: Cargo Check
      run: cargo check --verbose
    - name: Cargo Test
      run: cargo test --verbose
